from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.platypus.flowables import KeepTogether, PageBreakIfTooTall
from io import BytesIO
from datetime import datetime
import base64

class EnhancedPDFGenerator:
    def __init__(self):
        print("✅ Enhanced PDF Generator initialized!")
    
    def generate_claim_report(self, data):
        """Generate comprehensive PDF claim report"""
        buffer = BytesIO()
        # Further reduced margins for maximum text space
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=40,  # Further reduced
            leftMargin=40,   # Further reduced
            topMargin=50,    # Reduced
            bottomMargin=50  # Reduced
        )
        
        # Create story (content) for PDF
        story = []
        styles = self._get_styles()
        
        # 1. HEADER (more compact)
        header_text = """
        <para align=center spaceAfter=20>
        <font name="Helvetica-Bold" size=13 color=darkblue>
        CLAIM INSIGHT - INSURANCE CLAIM ASSESSMENT REPORT
        </font><br/>
        <font name="Helvetica" size=8 color=gray>
        AI-Powered Damage Assessment System
        </font>
        </para>
        """
        story.append(Paragraph(header_text, styles['Center']))
        story.append(Spacer(1, 0.1*inch))
        
        # 2. BASIC INFORMATION - Using Paragraphs instead of Table for better wrapping
        story.append(Paragraph(
            "<font name='Helvetica-Bold' size=10 color=darkblue>BASIC INFORMATION</font>",
            styles['Normal']
        ))
        story.append(Spacer(1, 0.05*inch))
        
        info_content = f"""
        <para leftIndent=10>
        <font name='Helvetica-Bold' size=9>Report Date:</font>
        <font name='Helvetica' size=9> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}<br/></font>
        
        <font name='Helvetica-Bold' size=9>Policy Holder:</font>
        <font name='Helvetica' size=9> {data.get('policy_holder_name', 'Not specified')}<br/></font>
        
        <font name='Helvetica-Bold' size=9>Contact Info:</font>
        <font name='Helvetica' size=9> {data.get('contact_email', '')} | {data.get('contact_phone', '')}<br/></font>
        
        <font name='Helvetica-Bold' size=9>Property Address:</font>
        <font name='Helvetica' size=9> {data.get('property_address', '')}, {data.get('city', '')}, {data.get('state', '')} {data.get('zip_code', '')}</font>
        </para>
        """
        story.append(Paragraph(info_content, styles['BodyText']))
        story.append(Spacer(1, 0.3*inch))
        
        # 3. RECOMMENDATIONS SECTION - Most important fix
        if 'recommendations' in data:
            story.extend(self._create_recommendations_section(data['recommendations'], styles))
        
        # 4. FOOTER
        story.append(PageBreakIfTooTall(0.5*inch))  # Ensure footer has space
        story.append(Spacer(1, 0.5*inch))
        footer_text = """
        <para align=center>
        <font name='Helvetica-Oblique' size=8 color=gray>
        This report was generated by Claim Insight AI System. For questions, contact support@claiminsight.com
        </font>
        </para>
        """
        story.append(Paragraph(footer_text, styles['Center']))
        
        # Build PDF
        doc.build(story)
        buffer.seek(0)
        return buffer
    
    def _get_styles(self):
        """Define custom styles for PDF with better text handling"""
        styles = getSampleStyleSheet()
        
        # Create a custom Normal style with optimal settings
        styles.add(ParagraphStyle(
            name='NormalWide',
            parent=styles['Normal'],
            fontSize=9,  # Smaller font
            leading=11,  # Tight but readable line spacing
            spaceAfter=6,
            spaceBefore=6,
            alignment=TA_JUSTIFY,  # Justified text
            wordWrap='LTR',  # Left-to-right word wrap
            splitLongWords=True,  # Allow splitting long words
            hyphenation=True  # Enable hyphenation
        ))
        
        styles.add(ParagraphStyle(
            name='BodyText',
            parent=styles['NormalWide'],
            fontSize=9,
            leading=12,
            spaceAfter=4,
            wordWrap='LTR',
            splitLongWords=True
        ))
        
        styles.add(ParagraphStyle(
            name='RecommendationItem',
            parent=styles['NormalWide'],
            fontSize=9,
            leading=12,
            leftIndent=0,
            spaceBefore=8,
            spaceAfter=8,
            alignment=TA_LEFT,
            wordWrap='LTR',
            splitLongWords=True
        ))
        
        styles.add(ParagraphStyle(
            name='Center',
            parent=styles['Normal'],
            alignment=TA_CENTER,
            fontSize=11,
            spaceAfter=6
        ))
        
        styles.add(ParagraphStyle(
            name='Bullet',
            parent=styles['NormalWide'],
            fontSize=9,
            leading=11,
            leftIndent=20,
            firstLineIndent=-15,
            wordWrap='LTR',
            splitLongWords=True
        ))
        
        # Style specifically for cost estimate to prevent cutoff
        styles.add(ParagraphStyle(
            name='CostEstimate',
            parent=styles['NormalWide'],
            fontSize=10,
            leading=14,
            spaceBefore=12,
            spaceAfter=12,
            alignment=TA_LEFT,
            wordWrap='LTR',
            splitLongWords=True,
            keepWithNext=True  # Keep cost estimate with its note
        ))
        
        return styles
    
    def _create_recommendations_section(self, recommendations, styles):
        """Create recommendations section with guaranteed text wrapping"""
        section = []
        
        # Section header
        section.append(Paragraph(
            "<font name='Helvetica-Bold' size=11 color=darkblue>RECOMMENDATIONS</font>",
            styles['NormalWide']
        ))
        section.append(Spacer(1, 0.05*inch))
        
        # Claim reference
        if 'claim_reference' in recommendations:
            section.append(Paragraph(
                f"<font name='Helvetica' size=9><b>Claim Reference:</b> {recommendations['claim_reference']}</font>",
                styles['NormalWide']
            ))
            section.append(Spacer(1, 0.15*inch))
        
        # Recommendations header
        section.append(Paragraph(
            "<font name='Helvetica-Bold' size=10>RECOMMENDATIONS:</font>",
            styles['NormalWide']
        ))
        section.append(Spacer(1, 0.1*inch))
        
        # Add each recommendation - CRITICAL FIX HERE
        for i, rec in enumerate(recommendations.get('items', []), 1):
            # Combine title and description in ONE paragraph for better wrapping
            rec_text = f"""
            <para>
            <font name='Helvetica-Bold' size=9>{i}. {rec.get('title', '')}</font><br/>
            <font name='Helvetica' size=9>{rec.get('description', '')}</font>
            </para>
            """
            
            section.append(Paragraph(rec_text, styles['RecommendationItem']))
            section.append(Spacer(1, 0.05*inch))
        
        section.append(Spacer(1, 0.2*inch))
        
        # COST ESTIMATE SECTION - Fixed to prevent cutoff
        if 'cost_estimate' in recommendations:
            # Cost estimate header
            section.append(Paragraph(
                "<font name='Helvetica-Bold' size=10>COST ESTIMATE GUIDANCE:</font>",
                styles['NormalWide']
            ))
            section.append(Spacer(1, 0.1*inch))
            
            # Main cost text - in ONE paragraph
            cost_text = f"""
            <para>
            <font name='Helvetica' size=9>
            Based on damage severity and affected components, the estimated repair cost falls within:
            </font>
            </para>
            """
            section.append(Paragraph(cost_text, styles['CostEstimate']))
            section.append(Spacer(1, 0.05*inch))
            
            # Cost range in bold
            section.append(Paragraph(
                f"<font name='Helvetica-Bold' size=11 color=darkred>{recommendations['cost_estimate']}</font>",
                styles['Center']
            ))
            section.append(Spacer(1, 0.1*inch))
            
            # Note - in ONE paragraph
            note_text = """
            <para>
            <font name='Helvetica' size=8 color=gray>
            <i>Note: This is a preliminary estimate. Actual costs may vary based on:</i>
            </font>
            </para>
            """
            section.append(Paragraph(note_text, styles['CostEstimate']))
            
            # Bullet points
            bullets = [
                "Labor rates in your area",
                "Parts availability",
                "Additional hidden damage",
                "Insurance coverage terms"
            ]
            
            for bullet in bullets:
                bullet_para = f"<font name='Helvetica' size=8 color=gray>• {bullet}</font>"
                section.append(Paragraph(bullet_para, styles['Bullet']))
                section.append(Spacer(1, 0.02*inch))
        
        return section